# Generated by Django 4.2.7 on 2023-11-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40, null=True)),
                ('descript', models.TextField(default='', null=True)),
                ('price', models.FloatField(default='', null=True)),
                ('quantity', models.IntegerField(default='', null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
